export const demoSops = [
  {
    id: 'rec-demo-1',
    taskName: 'Close out bar shift',
    category: 'Food & Beverage',
    duration: '0:52',
    poster: '/sop-posters/close-out-bar-shift.svg',
    video: { url: '/sop-videos/bar.mp4' },
    steps: {
      en: 'Wipe bar top\nStore garnishes\nCount till\nLock fridges',
      it: 'Pulisci il bancone\nMetti via le guarnizioni\nConta la cassa\nChiudi i frigoriferi',
      es: 'Limpia la barra\nGuarda las guarniciones\nCuenta la caja\nCierra los frigoríficos',
    },
  },
  {
    id: 'rec-demo-2',
    taskName: 'Housekeeping turnaround',
    category: 'Housekeeping',
    duration: '1:18',
    poster: '/sop-posters/housekeeping-turnaround.svg',
    video: { url: '/sop-videos/cleaning.mp4' },
    steps: {
      en: 'Strip linens\nDisinfect high-touch areas\nRestock amenities\nVacuum and inspect',
      it: 'Rimuovi le lenzuola\nDisinfetta le superfici\nRifornisci gli amenity\nPassa l’aspirapolvere e controlla',
      es: 'Retira las sábanas\nDesinfecta superficies\nReabastece amenities\nAspira y revisa',
    },
  },
  {
    id: 'rec-demo-3',
    taskName: 'Set up breakfast buffet',
    category: 'Food & Beverage',
    duration: '0:45',
    poster: '/sop-posters/set-up-breakfast-buffet.svg',
    video: { url: '/sop-videos/kitchen.mp4' },
    steps: {
      en: 'Sanitize surfaces\nSet chafing dishes\nLabel allergens\nRestock plates + cutlery',
      it: 'Sanifica le superfici\nPrepara i chafing dish\nEtichetta gli allergeni\nRifornisci piatti e posate',
      es: 'Desinfecta superficies\nPrepara bandejas\nEtiqueta alérgenos\nRepón platos y cubiertos',
    },
  },
  {
    id: 'rec-demo-4',
    taskName: 'Front desk check-in',
    category: 'Front Desk',
    duration: '1:05',
    poster: '/sop-posters/front-desk-check-in.svg',
    video: { url: '/sop-videos/front-desk.mp4' },
    steps: {
      en: 'Greet guest\nConfirm ID + payment\nExplain amenities\nHand over keys',
      it: 'Accogli l’ospite\nConferma documento e pagamento\nSpiega i servizi\nConsegna le chiavi',
      es: 'Saluda al huésped\nConfirma ID y pago\nExplica servicios\nEntrega llaves',
    },
  },
  {
    id: 'rec-demo-5',
    taskName: 'Night audit checklist',
    category: 'Front Desk',
    duration: '0:58',
    poster: '/sop-posters/night-audit-checklist.svg',
    video: { url: '/sop-videos/hotel.mp4' },
    steps: {
      en: 'Verify arrivals\nRun end-of-day\nPrint reports\nSecure cash drawer',
      it: 'Verifica arrivi\nChiudi giornata\nStampa report\nMetti in sicurezza la cassa',
      es: 'Verifica llegadas\nCierra el día\nImprime informes\nAsegura la caja',
    },
  },
  {
    id: 'rec-demo-6',
    taskName: 'Pool safety opening',
    category: 'Safety',
    duration: '0:40',
    poster: '/sop-posters/pool-safety-opening.svg',
    video: { url: '/sop-videos/pool.mp4' },
    steps: {
      en: 'Inspect deck\nCheck signage\nTest water\nLog readings',
      it: 'Ispeziona area\nControlla segnaletica\nTesta l’acqua\nRegistra i valori',
      es: 'Inspecciona área\nRevisa señalización\nPrueba el agua\nRegistra valores',
    },
  },
  {
    id: 'rec-demo-7',
    taskName: 'AC filter quick check',
    category: 'Maintenance',
    duration: '0:36',
    poster: '/sop-posters/ac-filter-quick-check.svg',
    video: { url: '/sop-videos/air-conditioner.mp4' },
    steps: {
      en: 'Power off unit\nRemove panel\nInspect filter\nReplace if needed',
      it: 'Spegni unità\nRimuovi pannello\nControlla filtro\nSostituisci se necessario',
      es: 'Apaga unidad\nQuita panel\nRevisa filtro\nCambia si hace falta',
    },
  },
  {
    id: 'rec-demo-8',
    taskName: 'Lost & found intake',
    category: 'Front Desk',
    duration: '0:50',
    poster: '/sop-posters/lost-and-found-intake.svg',
    video: { url: '/sop-videos/front-desk.mp4' },
    steps: {
      en: 'Tag item\nLog details\nStore securely\nNotify manager if valuable',
      it: 'Etichetta oggetto\nRegistra dettagli\nConserva in sicurezza\nAvvisa il manager se di valore',
      es: 'Etiqueta objeto\nRegistra detalles\nGuárdalo seguro\nAvisa al gerente si es valioso',
    },
  },
  {
    id: 'rec-demo-9',
    taskName: 'Room minibar restock',
    category: 'Housekeeping',
    duration: '0:44',
    poster: '/sop-posters/room-minibar-restock.svg',
    video: { url: '/sop-videos/cleaning.mp4' },
    steps: {
      en: 'Check inventory\nReplace missing items\nRecord charges\nSeal minibar',
      it: 'Controlla inventario\nRimpiazza mancanti\nRegistra addebiti\nSigilla minibar',
      es: 'Revisa inventario\nRepón faltantes\nRegistra cargos\nSella minibar',
    },
  },
  {
    id: 'rec-demo-10',
    taskName: 'Fire exit walk-through',
    category: 'Safety',
    duration: '0:55',
    poster: '/sop-posters/fire-exit-walk-through.svg',
    video: { url: '/sop-videos/alarm.mp4' },
    steps: {
      en: 'Check doors\nClear obstructions\nVerify signage\nLog issues',
      it: 'Controlla porte\nRimuovi ostacoli\nVerifica segnaletica\nRegistra problemi',
      es: 'Revisa puertas\nQuita obstáculos\nVerifica señalización\nRegistra incidencias',
    },
  },
  {
    id: 'rec-demo-11',
    taskName: 'Lobby floor spot clean',
    category: 'Housekeeping',
    duration: '0:38',
    poster: '/sop-posters/lobby-floor-spot-clean.svg',
    video: { url: '/sop-videos/cleaning.mp4' },
    steps: {
      en: 'Place wet floor sign\nSpot treat stains\nMop section\nRemove sign when dry',
      it: 'Metti cartello pavimento bagnato\nTratta macchie\nLava la zona\nRimuovi cartello a secco',
      es: 'Coloca señal\nTrata manchas\nFriega zona\nRetira señal al secar',
    },
  },
  {
    id: 'rec-demo-12',
    taskName: 'Kitchen closing sanitation',
    category: 'Food & Beverage',
    duration: '1:12',
    poster: '/sop-posters/kitchen-closing-sanitation.svg',
    video: { url: '/sop-videos/kitchen.mp4' },
    steps: {
      en: 'Discard perishables\nSanitize prep tables\nSweep + mop\nLock storage',
      it: 'Elimina deperibili\nSanifica tavoli\nSpazza e lava\nChiudi magazzino',
      es: 'Desecha perecederos\nDesinfecta mesas\nBarre y friega\nCierra almacén',
    },
  },
]
